import unittest
import Ordered_linked_list


class testlab4(unittest.TestCase):
    def test_simple(self):
        t_list = Ordered_linked_list.OrderedList()
        t_list.add(10)
        t_list.add(15)
        t_list.add(4)
        t_list.add(16)
        print(t_list.head.item)
        print(t_list.head.next.item)
        print(t_list.head.next.next.item)
        print(t_list.head.next.next.next.item)
        print(t_list.tail.item)
        t_list.remove(16)
        print(t_list.tail.item)
        t_list.remove(4)
        print(t_list.head.item)
        print(t_list.head.next.item)
        t_list.remove(16)
        print(t_list.head.item)
        print(t_list.tail.item)
        self.assertEqual(t_list.index(10), 0)
        self.assertEqual(t_list.index(15), 1)
        t_list.pop(1)
        print(t_list.tail.item)
        print(t_list.head.item)
        t_list.add(4)
        t_list.add(5)
        t_list.add(6)
        print(t_list.head.item)
        print(t_list.tail.item)
        print(t_list.head.next.item)
        print(t_list.head.next.next.item)
        print(t_list.head.next.next.next.item)
        print(t_list.python_list())
        print(t_list.search(10))
        print(t_list.search(11))
        print(t_list.python_list_reversed())
        print(t_list.size)
        print(t_list.remove(4))
        print(t_list.python_list())
        print(t_list.remove(10))
        print(t_list.remove(6))
        print(t_list.size)
        print(t_list.remove(5))
        print(t_list.size)
        print(t_list.python_list())
        print(t_list.is_empty())
        print(t_list.add(15))
        print(t_list.size)
        print(t_list.pop(0))